In [ ]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/dist-packages (0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sklearn) (1.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.7.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (3.1.0)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.21.6)

In [ ]:
pip install sklearn

In [ ]:
pip install TxtProc

In [ ]:
!pip install -i https://test.pypi.org/simple/ TxtProc==0.0.1

Looking in indexes: https://test.pypi.org/simple/, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: TxtProc==0.0.1 in /usr/local/lib/python3.7/dist-packages (0.0.1)
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/dist-packages (from TxtProc==0.0.1) (0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from TxtProc==0.0.1) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from TxtProc==0.0.1) (1.3.5)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from TxtProc==0.0.1) (3.7)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from nltk->TxtProc==0.0.1) (4.64.0)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from nltk->TxtProc==0.0.1) (7.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from nltk->TxtProc==0.0.1) (1.1.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.7/dist-packages (from nltk->TxtProc==0.0.1) (2022.6.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->TxtProc==0.0.1) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->TxtProc==0.0.1) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->TxtProc==0.0.1) (1.15.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sklearn->TxtProc==0.0.1) (1.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn->TxtProc==0.0.1) (1.7.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn->TxtProc==0.0.1) (3.1.0)

In [ ]:
import TxtProc as tp
import pandas as pd

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/the-fang/Spam-mail-filtering/master/spamham.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
# df.drop(['Category'],axis=1,inplace=True)

In [ ]:
proc = tp.Preprocess(df,"Message","Category")

In [ ]:
final = proc.preprocess()

>>>>Step 1: Removing Punctuations
>>>>Step 1 Successfully completed
>>>>Step 2: Lower casing all the letters
>>>>Step 2 Successfully completed
>>>>Step 3: Tokenization
>>>>Step 3 Successfully completed
>>>>Step 4: Removing stop words
>>>>Step 4 Successfully completed
>>>>Step 5: Stemming
>>>>Step 5 Successfully completed
>>>>Step 5: Lemmetization
>>>>Step 6 Successfully completed
>>>>Step 7: Bag of words
>>>>Step 7 Successfully completed
>>>>All text Preprocessing completed.

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
final.head()

,008704050406,0089my,0121,01223585236,01223585334,0125698789,02,020603,0207,02070836089,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,üll,〨ud,Category
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ham
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ham
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,spam
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ham
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ham

In [ ]:
final.columns

Index(['008704050406', '0089my', '0121', '01223585236', '01223585334',
       '0125698789', '02', '020603', '0207', '02070836089',
       ...
       'zhong', 'zindgi', 'zoe', 'zogtorius', 'zoom', 'zouk', 'zyada', 'üll',
       '〨ud', 'Category'],
      dtype='object', length=9274)